# Generated by Django 4.2 on 2023-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
