# Generated by Django 4.2 on 2023-04-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comm_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likediscomm',
            unique_together={('user', 'comm')},
        ),
    ]
