# Generated by Django 4.2 on 2023-04-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_likediscomm_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='likediscomm',
            name='id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likedissharebl',
            name='id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likediscomm',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.authuser'),
        ),
        migrations.AlterField(
            model_name='likedissharebl',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.authuser'),
        ),
        migrations.AlterUniqueTogether(
            name='likedissharebl',
            unique_together={('user', 'bl')},
        ),
    ]
