# Generated by Django 4.2 on 2023-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_likedissharebl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likediscomm',
            name='is_dis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='likediscomm',
            name='is_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='likedissharebl',
            name='is_dis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='likedissharebl',
            name='is_like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='likedissharebl',
            name='is_share',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='create_field',
            field=models.BooleanField(blank=True, db_column='create_', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='delete_comm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='red_ch',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='update_field',
            field=models.BooleanField(blank=True, db_column='update_', default=False, null=True),
        ),
    ]
